version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:14
    container_name: cdr_postgres
    environment:
      POSTGRES_DB: cdr_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  cdr-processor:
    build:
      context: ./cdr-processor
      dockerfile: Dockerfile
    container_name: cdr-processor
    depends_on:
      - kafka
      - postgres

  cdr-reporter:
    build:
      context: ./cdr-reporter
      dockerfile: Dockerfile
    container_name: cdr-reporter
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  cdr-generator:
    build:
      context: ./cdr-generator
      dockerfile: Dockerfile
    container_name: cdr-generator
    depends_on:
      - kafka

volumes:
  pgdata:
